### ISSUE TITLE
bug: Duplicated "neotest-busted-table-of-contents" when installed with lazy.nvim

### ISSUE THREAD

**Issue by polirritmico** [MisanthropicBit/neotest-busted#14]
Hi, I've just installed the plugin with lazy and is throwing this error:

```
        ...hare/nvim/lazy/lazy.nvim/lua/lazy/manage/task/plugin.lua:96: Vim:E154: Duplicate tag "neotest-busted-table-of-contents" in file /home/<myuser>/.local/share/nvim/lazy/neotest-busted/doc//neotest-busted.txt
```

And effectively, you have duplicated the table of contents section in the vimdoc file.

Maybe add some ignore tags to avoid this?

```markdown
<!-- panvimdoc-ignore-start -->

Table of contents

<!-- panvimdoc-ignore-end -->
```

**Comment by MisanthropicBit** [comment]
Nice catch, thanks for submitting an issue. I've made a fix for it, just need to test that it works properly and it should be fixed.
