### ISSUE TITLE
Use local busted installation

### ISSUE THREAD

**Issue by polirritmico** [MisanthropicBit/neotest-busted#22]
### Did you check docs and existing issues?

- [X] I have read the documentation
- [X] I have searched the existing issues
- [X] I have searched the existing issues of plugins related to this issue (if relevant)
- [X] I have tried setting `log_level` to `vim.log.levels.debug` in `neotest.setup` and examined the logs.

### Neovim version (nvim -v)

`NVIM v0.10.2 Build type: Release LuaJIT 2.1.1716656478`

### Operating system/version

Gentoo Linux 2.15, kernel 6.6.52-gentoo (64 bits)

### Describe the bug

Hi, I've been following this project from some time but I still can't get things working, most probably I'm setting something wrong. I don't know if this is possible at the current plugin state, but I want to use a local busted installed through a [lazy.nvim](https://lazy.folke.io/developers#minit-minimal-init) bootstrap. This is my `neotest` config:

```lua
{
  "nvim-neotest/neotest",
  dependencies = {
    "nvim-neotest/nvim-nio",
    "nvim-lua/plenary.nvim",
    "antoinemadec/FixCursorHold.nvim",
    "nvim-treesitter/nvim-treesitter",
    -- Adapters
    "MisanthropicBit/neotest-busted",
  },
  -- stylua: ignore
  keys = {
    { "<leader>rtf", function() require("neotest").run.run(vim.fn.expand("%")) end, desc = "neotest: Run all test in the current file" },
  },
  opts = {
    status = { virtual_text = true },
    output = { open_on_run = true },
    log_level = vim.log.levels.debug,
  },
  config = function(_, opts)
    opts.adapters = {
      require("neotest-busted")({
        busted_command = ".tests/data/nvim/lazy/busted/busted/runner.lua",
        busted_paths = {
          ".tests/data/nvim/lazy-rocks/busted/share/lua/5.1/pl/?.lua",
        },
        minimal_init = "tests/minit.lua",
        local_luarocks_only = true,
      }),
    }
    require("neotest").setup(opts)
  end,
},
```

But I'm getting not found modules errors when executing the tests:

```
E5113: Error while calling lua chunk: .tests/data/nvim/lazy/busted/busted/runner.lua:3: module 'pl.path' not found:
        no field package.preload['pl.path']
cache_loader: module pl.path not found
cache_loader_lib: module pl.path not found
        no file '.tests/data/nvim/lazy-rocks/busted/share/lua/5.1/pl/pl/path.lua'
        no file 'lua/pl/path.lua'
        no file 'lua/pl/path/init.lua'
        no file './pl/path.lua'
        no file '/usr/share/luajit-2.1/pl/path.lua'
        no file '/usr/local/share/lua/5.1/pl/path.lua'
        no file '/usr/local/share/lua/5.1/pl/path/init.lua'
        no file '/usr/share/lua/5.1/pl/path.lua'
        no file '/usr/share/lua/5.1/pl/path/init.lua'
        no file './pl/path.so'
        no file '/usr/local/lib/lua/5.1/pl/path.so'
        no file '/usr/lib64/lua/5.1/pl/path.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file './pl.so'
        no file '/usr/local/lib/lua/5.1/pl.so'
        no file '/usr/lib64/lua/5.1/pl.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'require'
        .tests/data/nvim/lazy/busted/busted/runner.lua:3: in main chunk
```

Also I got an error message complaining about a missing json test output (check the `neotest.log`).

Running the tests with: `nvim --clean -l tests/minit.lua --busted tests -o utfTerminal` work without any problem. I've made this [repo](https://github.com/polirritmico/foo.nvim) to provide the minimal environment. Check the reproduction steps.

### Expected Behavior

Found all the busted modules installed inside `.tests/data/nvim` path and run the tests through neotest without problems.

### Output of `:checkhealth neotest-busted` if relevant

Got this error:

```
- ERROR config has errors: busted command in configuration is not executable
- OK found `busted` (type: config) at
  /home/<username>/tmp/foo.nvim/.tests/data/nvim/lazy/busted/busted/runner.lua
```

But fixing that changing the `runner.lua` execution permissions **only** fix the checkhealth check:

```
neotest-busted ~
- WARNING vim.health.report_ok() is deprecated, use vim.health.ok() instead. :help |deprecated|
  Feature will be removed in Nvim 0.11
- OK has neovim 0.9.0+
- OK `neotest` is installed
- OK `nio` is installed
- OK found no errors in config
- OK found `busted` (type: config) at
  /home/<username>/tmp/foo.nvim/.tests/data/nvim/lazy/busted/busted/runner.lua
```

### neotest log output if relevant

```
ERROR | 2024-10-08T13:07:26Z-0300 | ...are/nvim/lazy/neotest-busted/lua/neotest-busted/init.lua:26 | Failed to read json test output file /tmp/nvim.<username>/HCE66a/0.json with error: ...al/share/nvim/lazy/neotest/lua/neotest/lib/file/init.lua:25: ENOENT: no such file or directory: /tmp/nvim.<username>/HCE66a/0.json
```

### Steps To Reproduce

```lua
-- repro.lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

if not vim.uv.fs_stat("foo.nvim") then
  vim.fn.system({ "git", "clone", "https://github.com/polirritmico/foo.nvim.git" })
end

require("lazy.minit").repro({
  spec = {
    { "folke/tokyonight.nvim", enabled = false },
    {
      "nvim-neotest/neotest",
      dependencies = {
        "nvim-neotest/nvim-nio",
        "nvim-lua/plenary.nvim",
        "antoinemadec/FixCursorHold.nvim",
        "nvim-treesitter/nvim-treesitter",
        -- Adapters
        "MisanthropicBit/neotest-busted",
      },
    -- stylua: ignore
    keys = {
      { "<leader>rtf", function() require("neotest").run.run(vim.fn.expand("%")) end, desc = "neotest: Run all test in the current file" },
      { "<leader>rto", function() require("neotest").output_panel.toggle() end, desc = "neotest: Toggle output panel" },
      { "<leader>rtp", function() require("neotest").summary.toggle() end, desc = "neotest: Toggle summary panel" },
    },
      opts = {
        status = { virtual_text = true },
        output = { open_on_run = true },
      },
      config = function(_, opts)
        opts.adapters = {
          require("neotest-busted")({
            busted_command = ".tests/data/nvim/lazy/busted/busted/runner.lua",
            busted_paths = {
              ".tests/data/nvim/lazy-rocks/busted/share/lua/5.1/pl/?.lua",
            },
            minimal_init = "tests/minit.lua",
            local_luarocks_only = true,
          }),
        }
        require("neotest").setup(opts)
      end,
    },
  },
})

vim.cmd("cd foo.nvim")
vim.cmd("edit tests/neotest_spec.lua")
```

0. Add the `repro.lua` file to an empty directory.
1. Execute the `repro.lua` file through nvim: `nvim -u repro.lua` and exit nvim.
2. Inside `foo.nvim`, run the tests through the bootstrap: `cd foo.nvim`, `nvim --clean -l tests/minit.lua --busted tests -o utfTerminal`
3. Should install the environment and run the tests with 1 success and 1 failure
4. Again, run the repro: `cd ..`, `nvim -u repro.lua`
5. And run neotest: `:lua require("neotest").run.run(vim.fn.expand("%"))`
6. Error:

```
Failed to read json test output file /tmp/nvim.<username>/4gO8hc/2.json with error: ...al/share/nvim/lazy/neotest/lua/neotest/lib/file/init.lua:25: ENOENT: no such file or directory: /tmp/nvim.<username>/4gO8hc/2.json
Press ENTER or type command to continue
```

---

Don't know if more info is needed.

Thanks!

**Comment by MisanthropicBit** [comment]
Hi again @polirritmico. Thanks for submitting another issue and providing a detailed description. Really helps with debugging! 🙂

I'm currently on holiday and away from my computer. I'll be home next week where I can try your repro and provide more help.

A few things regarding the errors etc.

* The error you get regarding `pl.path` indicates that there are missing/incorrect paths set up for busted. IIRC, busted depends on the penlight library which is packaged as a shared library (.so on your system). If I'm correct, you'll need to set up `busted_cpaths` in the config as well.
* The healthcheck is complaining that `runner.lua` is not executable which is correct since it's just a lua source file. The command you are looking for is an executable file called `busted` in your local luarocks installation directory.
* You can check this part of the adapter for the paths it looks for when searching for an executable and paths: https://github.com/MisanthropicBit/neotest-busted/blob/master/lua/neotest-busted/init.lua#L51.
* If your local busted installation is in the same directory as the bootstrap (I'm assuming you did a manual local install of busted via luarocks or perhaps the option `--busted` does this?) then you shouldn't need to specify `busted_command` and `busted_paths` as neotest-busted will automatically first look for a local installation and then a user (home-directory) and finally a global installation. The two latter installations are only searched for if `local_luarocks_only` is `false`.
* Regarding the last error about the nonexistent json file, I think that neotest fails to run the test command for the reasons listed above which generates no results and no json file, so when neotest calls the adapter to get results, neotest-busted tries to read a json file that was never created. Perhaps there's a way to signal neotest that the adapter failed at a certain point so this error message is removed.

Hope that helps for now.

**Comment by polirritmico** [comment]
Hi. Thanks for the info. Finally I was able to get things running.
I had to:

1. update the minimal_init file:

```lua
#!/usr/bin/env -S nvim -l

Remote = false
vim.env.LAZY_STDPATH = ".tests"
local url = "https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"

if Remote then
  load(vim.fn.system("curl -s " .. url))()
else
  local bootstrap = ".tests/bootstrap.lua"
  if not vim.uv.fs_stat(bootstrap) then
    vim.fn.mkdir(vim.fs.dirname(bootstrap), "p")
    vim.fn.system("curl -s " .. url .. " -o " .. bootstrap)
  end
  loadfile(bootstrap)()
end

-- Setup lazy.nvim
require("lazy.minit").busted({
  spec = {},
})
```

2. remove the old bootstrap

```sh
$ rm -rf .tests
```

3. update the neotest-busted config:

```lua
require("neotest-busted")({
  busted_command = ".tests/data/nvim/lazy/busted/bin/busted",
  minimal_init = "tests/busted.lua",
  local_luarocks_only = true,
}),
```

5. Run the new bootstrap

```sh
$ nvim -l tests/minit.lua tests
```

7. And finally run neotest!:

![imagen](https://github.com/user-attachments/assets/98779c00-e179-4dc3-9f47-554cf02b25cd)

Thanks for the help!
